version: 1

formatters:
  default:
    format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s'
    datefmt: '%H:%M:%S'
  extended:
    format: '[%(asctime)s] %(levelname)s in %(module)s: %(message)s [%(pathname)s:%(lineno)d]'
    datefmt: '%H:%M:%S'

handlers:
  console:
    class: 'logging.StreamHandler'
    stream: 'ext://flask.logging.wsgi_errors_stream'
    formatter: 'default'
  file:
    class: 'logging.handlers.RotatingFileHandler'
    filename: 'server.log'
    delay: true
    maxBytes: 10485760
    backupCount: 20
    formatter: 'extended'

loggers:
  master:
    level: 'DEBUG'
    handlers: ['console', 'file']